name: Build and Push to ACR

# Esto hace que el proceso empiece cada vez que hacemos "git push"
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Descarga nuestro código en la máquina de GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Inicia sesión en el Azure Container Registry usando los Secrets
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 3. Construye la imagen Docker y la sube al ACR
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/horizonte-azul:latest -f Dockerfile .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/horizonte-azul:latest